# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ocr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ocr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tocr.proto\x12\x03ocr\"?\n\nOcrRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x1a\n\x03roi\x18\x02 \x01(\x0b\x32\x08.ocr.RoiH\x00\x88\x01\x01\x42\x06\n\x04_roi\"?\n\x03Roi\x12\x0c\n\x04left\x18\x01 \x01(\x02\x12\x0b\n\x03top\x18\x02 \x01(\x02\x12\r\n\x05right\x18\x03 \x01(\x02\x12\x0e\n\x06\x62ottom\x18\x04 \x01(\x02\"U\n\x0bOcrResponse\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.ocr.OcrItem\x12\x1a\n\x12processing_time_ms\x18\x02 \x01(\x02\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"`\n\x07OcrItem\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x12\x12\n\nconfidence\x18\x06 \x01(\x02\"\x0f\n\rHealthRequest\"B\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65vice\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t2o\n\nOcrService\x12.\n\tRecognize\x12\x0f.ocr.OcrRequest\x1a\x10.ocr.OcrResponse\x12\x31\n\x06Health\x12\x12.ocr.HealthRequest\x1a\x13.ocr.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OCRREQUEST']._serialized_start=18
  _globals['_OCRREQUEST']._serialized_end=81
  _globals['_ROI']._serialized_start=83
  _globals['_ROI']._serialized_end=146
  _globals['_OCRRESPONSE']._serialized_start=148
  _globals['_OCRRESPONSE']._serialized_end=233
  _globals['_OCRITEM']._serialized_start=235
  _globals['_OCRITEM']._serialized_end=331
  _globals['_HEALTHREQUEST']._serialized_start=333
  _globals['_HEALTHREQUEST']._serialized_end=348
  _globals['_HEALTHRESPONSE']._serialized_start=350
  _globals['_HEALTHRESPONSE']._serialized_end=416
  _globals['_OCRSERVICE']._serialized_start=418
  _globals['_OCRSERVICE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
